<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-I6VULTJ" failures="4" tests="19" name="Test" time="14.284" errors="0" timestamp="2025-08-12T21:15:46 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="6.411"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.473"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.359"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.388"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.281">
    <failure type="java.lang.AssertionError" message="Response is not JSON!!!
Expected: a string containing &amp;quot;application/json&amp;quot;
     but: was &amp;quot;&amp;quot;">
      <![CDATA[java.lang.AssertionError: Response is not JSON!!!
Expected: a string containing "application/json"
     but: was ""
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at utils.ValidationUtils.validateResponse(ValidationUtils.java:15)
at stepdefinations.GetInvalidSteps.validate_the_get_by_invalidid_response(GetInvalidSteps.java:26)
at ✽.validate the get by invalidid response(file:///C:/Users/DELL/eclipse-workspace/RestAssuredTestingCucumber/src/test/resources/feature/BookingAPI.feature:30)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.337"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.379">
    <failure type="java.lang.AssertionError" message="StatusCode mismatch!!!
Expected: &amp;lt;404&amp;gt;
     but: was &amp;lt;200&amp;gt;">
      <![CDATA[java.lang.AssertionError: StatusCode mismatch!!!
Expected: <404>
     but: was <200>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at utils.ValidationUtils.validateStatusCode(ValidationUtils.java:21)
at stepdefinations.DelInvalidIdSteps.validate_the_del_by_invalidid_response(DelInvalidIdSteps.java:29)
at ✽.validate the del by invalidid response(file:///C:/Users/DELL/eclipse-workspace/RestAssuredTestingCucumber/src/test/resources/feature/BookingAPI.feature:40)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.888"/>
  <testcase classname="testcases.AuthAccessTest" name="getAccessToken" time="0.014"/>
  <testcase classname="testcases.GetListTest" name="getList" time="0.281"/>
  <testcase classname="testcases.GetTrainTest" name="getByTrainClass" time="0.268"/>
  <testcase classname="testcases.PostBookingTest" name="getBooking" time="0.28"/>
  <testcase classname="testcases.PostBookingTest" name="postBooking" time="0.356"/>
  <testcase classname="testcases.DeleteIdTest" name="deleteById" time="0.235"/>
  <testcase classname="testcases.DeleteIdTest" name="getBooking" time="0.278"/>
  <testcase classname="testcases.DelInvalidIdTest" name="deleteByInvalidId" time="0.258">
    <failure type="java.lang.AssertionError" message="Response must be null!!! expected [null] but found [io.restassured.internal.RestAssuredResponseImpl@41f40dfa]">
      <![CDATA[java.lang.AssertionError: Response must be null!!! expected [null] but found [io.restassured.internal.RestAssuredResponseImpl@41f40dfa]
at testcases.DelInvalidIdTest.deleteByInvalidId(DelInvalidIdTest.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteByInvalidId -->
  <testcase classname="testcases.DelInvalidIdTest" name="getBooking" time="0.294"/>
  <testcase classname="testcases.GetIdTest" name="getById" time="0.289"/>
  <testcase classname="testcases.GetInvalidIdTest" name="getByInvalidId" time="0.296">
    <failure type="java.lang.AssertionError" message="Response must be null!!! expected [null] but found [io.restassured.internal.RestAssuredResponseImpl@6fcc0a1]">
      <![CDATA[java.lang.AssertionError: Response must be null!!! expected [null] but found [io.restassured.internal.RestAssuredResponseImpl@6fcc0a1]
at testcases.GetInvalidIdTest.getByInvalidId(GetInvalidIdTest.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- getByInvalidId -->
</testsuite> <!-- Test -->
